pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
    actions:
      merge:
        method: merge
  - name: automatic merge for Imgbot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge